// <auto-generated />
namespace NSDBz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NSDBz3Test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NSDBz3Test));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111813076_NSDBz3Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
